- hosts: debian-8 , debian-9 , ubuntu-12 , ubuntu-14 , ubuntu-16 , ubuntu-18
  become: no
  tasks:
    - name: Create scripts directory
      file: dest=/opt/ansible/bin mode=755 owner=root group=staff state=directory

    - name: Copy script to server
      copy: src=check_CVE-2019-3462.sh dest=/opt/ansible/bin/check_CVE-2019-3462.sh mode=755 owner=root group=staff

    - name: Check apt version
      command: /opt/ansible/bin/check_CVE-2019-3462.sh
      become: no
      register: output

    - debug: var=output.stdout_lines
